[package]
name = "frontend"
version = "0.1.0"
authors = ["oScape <benoit.chassignol@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17.4"
yew-components = "0.2.0"
wasm-bindgen = "0.2.68"
chrono = "0.4.19"
js-sys = "0.3.45"