[package]
name = "frontend"
version = "0.1.0"
authors = ["oScape <benoit.chassignol@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
yew-components = "0.2"
wasm-bindgen = "0.2.67"
chrono = "0.4.19"